### ISSUE TITLE
Please provide a software site for simple installing

### ISSUE THREAD

**Issue by admiralsmaster** [pbi-qfs/ecd#2]
Could you please provide a software/update page? This would simplify installation. Perhaps you can use the gh-pages branch of this repository.

And a big praise for what you do.

**Comment by RobertZenz** [comment]
We are in the process of reviewing the whole code and fixing problems we find. Please give us a little time to do that as there still a few corners we have to figure out (in the code and on the project management side). Our goal is to get it out there as soon as we can manage, with as little modifications as we can manage.

Personally, I'd like to have the Marketplace entry up and running some when in the next week (because I really want to have it back in my work setup), but please don't take that as some sort of official plan. We are in the process of getting there.

**Comment by pbi-qfs** [comment]
@admiralsmaster: Can you try if http://pbi-qfs.github.io/ecd/update works as an update site for your? We're still in the progress of getting it running properly

**Comment by sgwerder** [comment]
Update site worked for me. Thanks!

**Comment by pbi-qfs** [comment]
@sgwerder: Yes, we'll try within the next days.

**Comment by admiralsmaster** [comment]
Yes, runs...

Thank you again.

**Comment by ecd-plugin** [comment]
@admiralsmaster @sgwerder: We changed the github location of the fork, so please update the Update-Site URL to http://ecd-plugin.github.io/update

Sorry for the inconvenience.

**Comment by pbi-qfs** [comment]
The plugin is (re)-listed now at the Eclipse Marketplace:
https://marketplace.eclipse.org/content/enhanced-class-decompiler
